services:
  - type: web
    name: poultry-backend
    runtime: docker
    plan: free
    region: oregon # Based on your previous screenshot
    buildFilter:
      paths:
      - "apps/backend/**"
      - "packages/**"
      - "package.json"
      - "package-lock.json"
      - "Dockerfile"
    # The following settings are crucial for a monorepo
    dockerContext: .
    dockerfilePath: ./Dockerfile
    releaseCommand: "npx prisma generate && npx prisma migrate deploy"
    startCommand: "npm run start:prod --workspace=@poultry-marketplace/backend"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: poultry-db # This will be the name of your new database
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: "https://your-frontend-url.vercel.app" # Replace with your frontend URL after deploying it

databases:
  - name: poultry-db
    plan: free 