services:
  - type: web
    name: poultry-backend
    runtime: docker
    plan: free
    region: oregon # Based on your previous screenshot
    # The following settings are crucial for a monorepo
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: poultry-db # This will be the name of your new database
          property: connectionString
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: "https://your-frontend-url.vercel.app" # Replace with your frontend URL after deploying it

databases:
  - name: poultry-db
    plan: free 